/**
 * Contributions feed — /public/contributions/index.json (generated by
 * scripts/fetch-contributions.mjs). Shared by the home strip and the
 * contributions page. Only published advisories are surfaced; patches
 * and reports stay in the JSON but are filtered out here.
 */

export interface Contribution {
  id: string
  /** "patch" (PR) | "advisory" */
  type: string
  title: string
  summary: string
  repo: string
  url: string
  /** ISO datetime */
  date: string
  /** "merged" | "published" | "open" | … */
  state: string
  tags: string[]
  /** CVE identifier, present on advisories when known */
  cveId?: string
}

let cache: Contribution[] | null = null

/** All published advisories, newest first. Cached after first fetch. */
export async function loadContributions(): Promise<Contribution[]> {
  if (cache) return cache
  const res = await fetch('/contributions/index.json')
  if (!res.ok) throw new Error(`failed to load contributions: ${res.status}`)
  const raw = (await res.json()) as { items: Contribution[] }
  cache = [...(raw.items ?? [])]
    .filter((it) => it.type === 'advisory' && it.state === 'published')
    .sort((a, b) => (a.date < b.date ? 1 : -1))
  return cache
}

/** "08 Jun 2026" */
export function formatContributionDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-GB', {
      day: '2-digit',
      month: 'short',
      year: 'numeric',
      timeZone: 'UTC',
    })
  } catch {
    return iso
  }
}
